# Generated by Django 5.2.11 on 2026-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Enter one point per line (optional)'),
        ),
    ]
