# Generated by Django 5.2.11 on 2026-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_program_bullet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
    ]
