# Generated by Django 5.2.11 on 2026-03-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_teammember_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
